# Do not use this compose file for production deployments
services:

  carbon-redis:
    image: redis:alpine
    command: redis-server --save 300 1 --loglevel warning
    networks:
      - private
    volumes:
      - /data/carbon/redis:/data
    environment:
      SKIP_DROP_PRIVS: 1

  carbon-frontend:
    build:
      context: ./web
      no_cache: true
      args:
        GIT_TAG: ${GIT_TAG:?Error GIT_TAG is missing}
    image: cert-edf/carbon-fe
    pull_policy: build
    ports:
      - 127.0.0.1:8121:80

  carbon-backend:
    build:
      context: ./server/docker
      no_cache: true
    image: cert-edf/carbon-be
    pull_policy: build
    ports:
      - 127.0.0.1:8111:8080
    networks:
      - default
      - private
    volumes:
      - /data/carbon/conf:/conf
      - /data/carbon/data:/data
    depends_on:
      - carbon-redis
    environment:
      ROLE: server
      FUSION_DEBUG: 0

  carbon-synchronizer:
    build:
      context: ./server/docker
      no_cache: true
    image: cert-edf/carbon-be
    pull_policy: build
    volumes:
      - /data/carbon/conf:/conf
      - /data/carbon/data:/data
    environment:
      ROLE: synchronizer
      FUSION_DEBUG: 0

networks:
  private:
